### ISSUE TITLE
Livewire does not work for central domains when using Single Database Tenancy

### ISSUE THREAD

**Issue by devsquad-eduardo-barijan** [stancl/tenancy#1115]
### Bug description

In a project configured to use Single Database Tenancy, following the docs (https://tenancyforlaravel.com/docs/v3/single-database-tenancy/) that is using Livewire for tenants, when using Livewire for central domain, it does not work at all.

Livewire is configured following the docs too (https://tenancyforlaravel.com/docs/v3/integrations/livewire)

---

<img width="943" alt="Screenshot 2023-05-26 at 10 09 16" src="https://github.com/archtechx/tenancy/assets/103602376/f2d2c426-ecb8-4f68-8812-ac861307b317">

### Steps to reproduce

- Install Livewire: `composer require livewire/livewire`
- Install Tenancy
- Configure to use Single Database
- Configure multiple central domains for testing, like the following:

```
'central_domains' => [
        '127.0.0.1',
        'localhost',
        'project.test',
        'project-app.test',
        'project-staging.yourcompany.app',
    ],
```

- Enable Universal Routes, following the documentation
- Edit `config/livewire.php` to enable the universal middleware:

```
 'middleware_group' => [
        'web',
        'universal',
        InitializeTenancyByDomain::class,
    ],
```

- create a livewire component: `php artisan make:livewire Register`
- edit `App\Http\Livewire\Register.php` and add the save() method:

```
public function save()
    {
        dump('saving in register component');
    }
```

- edit `resources\views\livewire\register.blade.php` and add a button or link with a `wire:click` to call the save method:

```
<div>
    this is a test of the register component
    <button type="button" wire:click="save">Save register</button>
</div>
```

- edit `routes\web.php` and add a route for the Register component:

```
use App\Http\Livewire\Register;
use Illuminate\Support\Facades\Route;

Route::get('register-live', Register::class);
```

- Go to browser and access your central domain with register-live route: `http://project.test/register-live`
- Click the `Save register` button

### Expected behavior

- it should display the dump message in the Livewire modal window

### Laravel version

9.52.7

### stancl/tenancy version

3.7.0

**Comment by stancl** [comment]
Could you provide console logs

**Comment by devsquad-eduardo-barijan** [comment]
Yes, but it doesn't show much, I am afraid. I provide the console log and the network request that Livewire is trying to do

---

<img width="566" alt="Screenshot 2023-05-26 at 21 57 52" src="https://github.com/archtechx/tenancy/assets/103602376/1b3c240e-0304-4590-830c-9ea3c3106540">

<img width="664" alt="Screenshot 2023-05-26 at 21 58 46" src="https://github.com/archtechx/tenancy/assets/103602376/457a612b-ee57-43f5-8f84-e322cb95a83b">

**Comment by chopstik** [comment]
I've had this issue happen today on our multi-tenant app as well. Livewire click events on the central domain would fire and hit the component method, but 404 return by `abort()` whch appeared to be thrown via the PreventAccessFromCentralDomain middleware even though the route was in the web/central space.

**Comment by devsquad-eduardo-barijan** [comment]
@chopstik in your case it is hitting the component method. Maybe it has to do with Laravel version, some internals on how the universal routing works. I just realized I did test with Laravel 9 and not 10 yet. 

Then again, Livewire does work inside the tenant routes. Checking the docs, I didn't find a way to like, disconnect a tenant or revert back to central. I think that approach would work, if using in a middleware for instance. What do you think @stancl ?

**Comment by stancl** [comment]
We couldn't reproduce this in a testing app using Tenancy v4, so it seems like this has been solved in v4 👍

**Comment by chopstik** [comment]
@stancl why close this? v4 is not available and using L v9 & Tenancy v3 the issue persists does it not?

**Comment by stancl** [comment]
1. There's no actual bug in the package, this relates to integrating a third party package with a very specific setup. And there's no guaranteed support for third party packages, we only have integration _guides_ that may be helpful
2. v4 had many changes relating to how routing and package integrations work, so there's no easy way for us to port that to v3 since we can't easily see any single thing that causes this to work fine in v4 (at least in our tests) but not in v3

Currently v4 is available in early access for sponsors and will likely be released in the coming months.

**Comment by chopstik** [comment]
I'm not integrating a third party package though, which package are you referring to? 
Why is it a 'very specific setup'? 
I've a multi-tenant database setup using just your package and your documentation. I'm using Universal Routes. 
The component method I refer to is is a simple Livewire Counter example, one button, one click increments the counter. I have duplicated that method to allow access from from a 'web' route and a 'tenant' route. This Counter method works on the tenant route but not on the web route, it appears PreventAccessFromCentralDomain middleware is aborting the request even though its a 'web' route and not a 'tenant' route.

**Comment by chopstik** [comment]
Which is a similar situation to the one @devsquad-eduardo-barijan  raised above.

**Comment by stancl** [comment]
> I'm not integrating a third party package though, which package are you referring to?

Livewire is a third-party package.

> I've a multi-tenant database setup using just your package and your documentation. I'm using Universal Routes.
The component method I refer to is is a simple Livewire Counter example, one button, one click increments the counter

This is a different setup from what this person is using. Livewire with multi-domain multi-db works fine (our boilerplate uses it) so it sounds like there's some confusion here.

If you have a support question, I recommend asking on our Discord.

**Comment by stancl** [comment]
Also even regarding the setup being used in the original post, I personally think it should work without issues and there must be some misconfiguration going on. But we couldn't reproduce this in our tests so there's no bug to fix in v4, so you can either try v4 or double check your configuration/ask on our Discord.

**Comment by devsquad-eduardo-barijan** [comment]
The issue is solved, indeed. The product's code was using a custom middleware, that we ported to the tests previously, that was causing the issues mentioned. We redid the tests with a real vanilla setup this time, replicating each step to the product and yeah, we figured out some misbehaviour with the `forceRootUrl()` method.

For reference, those lines are indeed rewritting the requests to use a specific URL, from a Settings model:

```php
public function bootstrap(): void
    {
        $this->url = Settings::get(SettingKey::BASE_URL);

        $this->general();
    }

    private function general(): void
    {
        config()->set('app.url', $this->url);

        app('url')->forceRootUrl($this->url);
    }
```
I don't know how v4 changed the routing scheme, but maybe give it a check so forceRootUrl behaves correctly with tenant-aware routes, or make a change to docs to warn potential developers for this technique.

We will refactor this middleware that is supposed to get a tenant's specific settings from the database, to use `configs by tenant` from this package.

Thank you very much for your patience and time to look at this particular setup and issue
